nama            = input ("Nama                  :")
nim             = input ("NIM                   :")
kelas_paralel   = input ("Kelas Paralel         :")
ttl             = input ("Tempat/Tanggal Lahir  :")
alamat          = input ("Alamat                :")
hobby           = input ("Hobby                 :")
no_hp           = input ("No. HP                :")
print("\n")

print("Nama                    :", nama)
print("NIM                     :", nim) 
print("Kelas Paralel           :", kelas_paralel)
print("Tempat/Tanggal Lahir    :", ttl)
print("Alamat                  :", alamat) 
print("Hobby                   :", hobby)
print("No. HP                  :", no_hp)